osc=no
osd-level=0
osd-bar=no

no-window-dragging
keep-open=yes
ontop
no-border

hwdec=no
vo=gpu
gpu-context=x11egl
no-keepaspect

cache=yes
demuxer-seekable-cache=yes
demuxer-readahead-secs=300
demuxer-max-bytes=4000M
demuxer-max-back-bytes=4000M

force-seekable=yes
prefetch-playlist=yes
