osc=no
osd-level=0
osd-bar=no

no-window-dragging
keep-open=yes
ontop
no-border

hwdec=no
no-keepaspect

force-seekable=yes
prefetch-playlist=yes

network-timeout=30
cache-secs=60
demuxer-readahead-secs=30
